//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Miembro()
        {
            this.EventoMiembro = new HashSet<EventoMiembro>();
        }
    
        public string idMiembro { get; set; }
        public string nombre { get; set; }
        public string numeroCedula { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Confirmo { get; set; }
        public Nullable<int> Elimino { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoMiembro> EventoMiembro { get; set; }
    }
}
